### ISSUE TITLE
How to change skin of the editor

### ISSUE THREAD

**Issue by uisumo** [dangvanthanh/vue-ckeditor2#103]
Hi,

Thanks for this great work.

**Is there a way to change the skin of the editor?**

I tried with config skin name 'kama' it's not taking.

Any idea.

Thanks,

**Comment by dangvanthanh** [comment]
Hi @uisumo 

You can change skin by this way. The first you download Ckeditor then download skin. Example use `kama`, you can download [Kama skin](https://ckeditor.com/cke4/addon/kama)

Extract zip and copy skin file to `skin` folder. Example `<CKEditor folder>/skins/kama`

Finally, you config skin for Ckeditor

```vue
<template>
  <div>
    <vue-ckeditor 
      v-model="content" 
      :config="config" />
  </div>
</template>

<script>
import VueCkeditor from 'vue-ckeditor2';

export default {
  components: { VueCkeditor },
  data() {
    return {
      content: '',
      config: {
        toolbar: [
          ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
        ],
        height: 300,
        skin: 'kama'
      }
    };
  }
};
</script>
```
