### ISSUE TITLE
Use placeholder

### ISSUE THREAD

**Issue by silvio-gratani** [dangvanthanh/vue-ckeditor2#104]
Just trying to set a placeholder without any luck, my version is 2.1.5.

Already found issue #60 and used both the `extraPlugins` and `placeholder` params in `config`, my code is
```
config: {
    toolbar: [
        [...]
    ],
    extraPlugins: 'placeholder',
    placeholder: 'test placeholder',
    height: 300,
}
```
But i still get this error in vrowser console:
```
ckeditor.js:268 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "placeholder" was not found at "https://cdn.ckeditor.com/4.12.1/standard/plugins/placeholder/plugin.js?t=J5S8".
```
The given link lead to a 404 page.

**Comment by dangvanthanh** [comment]
Hi @silvio-gratani 

You use Ckeditor 4 with `standard` preset. But `standard` preset isn't contains `placeholder` plugin. You need to to `full` preset

```
https://cdn.ckeditor.com/4.12.1/full/ckeditor.js
```

or `full-all` preset

```
https://cdn.ckeditor.com/4.12.1/full-all/ckeditor.js
```

for resolve it.
