### ISSUE TITLE
v-model not working

### ISSUE THREAD

**Issue by ammadmaddydev** [dangvanthanh/vue-ckeditor2#105]
V-model is not updating variable value. 

template code:
![image](https://user-images.githubusercontent.com/26835424/104201275-6218b980-544b-11eb-8404-41edeb0e2138.png)

JS Code:
![image](https://user-images.githubusercontent.com/26835424/104200862-f33b6080-544a-11eb-8973-4e075b89be41.png)

On Save Button i want to get all updated information but ckeditor is not updating variable value that's why it's showing blank inside it:
![image](https://user-images.githubusercontent.com/26835424/104200902-ff272280-544a-11eb-85dc-433b49e8ee59.png)

Here is the output:
![image](https://user-images.githubusercontent.com/26835424/104201381-82e10f00-544b-11eb-89f4-ec1cbe665249.png)

**Comment by dangvanthanh** [comment]
Hi @ammadmaddydev 

I will investigate and fix it soon.

**Comment by dangvanthanh** [comment]
Hi @ammadmaddydev 

I was tested with `vue-ckeditor2` version `2.1.5` and `ckedior.js` version `4.15.1`

```html
<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
```

The content is updating when you enter to save button.

This is my code:

```vue
<template>
  <div>
    <template v-for="(section, index) in pageSections">
      <VueCkeditor v-model="section.content" :config="section.config" :key="index" />
    </template>
    <br />
    <button @click.prevent="handleSave">Save</button>
  </div>
</template>

<script>
import VueCkeditor from 'vue-ckeditor2'

export default {
  name: 'TestVueCkeditor',
  components: { VueCkeditor },
  data() {
    return {
      pageSections: [
        {
          name: '',
          sort: '',
          content: '',
          removeable: 0,
          config: {
            toolbar: [['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']],
            height: 300,
          },
        },
      ],
    }
  },
  methods: {
    handleSave() {
      console.log(this.pageSections)
    },
  },
}
</script>

<style scoped>
h1 {
  padding: 0 0.25em;
}
</style>
```

and this is the result when I enter content

![Screen Shot 2021-01-14 at 20 44 39](https://user-images.githubusercontent.com/2674850/104599028-dc467980-56a9-11eb-9420-528872330e05.png)

**Comment by ammadmaddydev** [comment]
Hi @dangvanthanh,
I was using ckeditor 4.1 script. that's why it was not working. Later I had updated it to 4.15 then it was fine.
Thanks for your support.
