### ISSUE TITLE
Multiple usage of component

### ISSUE THREAD

**Issue by dermansi** [dangvanthanh/vue-ckeditor2#106]
Thank you for creating this component!

We are using this component multiple times (like many many times) on the same page. Sadly it loads the editor assets again with every component which slows initial page load down quite a bit:
![image](https://user-images.githubusercontent.com/14231192/106163138-22f7a180-6189-11eb-9c8d-527d57f9b69d.png)

Is there a way to avoid this?

**Comment by dangvanthanh** [comment]
Hi @dermansi 

Every time using CKEditor, each editor will load each specifies asset (such as the `CSS` file) for each editor. I see the same your issues on https://ckeditor.com/docs/ckeditor4/latest/examples/classic.html#editor1

But I will investigate for load 1 assets for multiple editors. 

Thank you for contributing the issue for this component.
