### ISSUE TITLE
toolbar parameter should accept String type too.

### ISSUE THREAD

**Issue by comfuture** [dangvanthanh/vue-ckeditor2#13]
According to ckeditor documents, `toolbar` option can be String/Array.
Simply "Basic" will fills value of `config.toolbar_Basic`.

* See: http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-toolbar

**Comment by dangvanthanh** [comment]
@comfuture Thank you. I will update toolbar can be using String and Array

**Comment by comfuture** [comment]
please refer to pr #15
