### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by murilolivorato** [dangvanthanh/vue-ckeditor2#14]
Hello my friend . It is giving me an errro .
I am using vue 2 .

![error5](https://cloud.githubusercontent.com/assets/19832238/23920929/5ff0b7da-08db-11e7-8423-5fd3e3deb778.jpg)

Can you have a look ?

Thanks

**Comment by dangvanthanh** [comment]
@murilolivorato Can you show me code you using with vue-ckeditor2

**Comment by LeungKaMing** [comment]
Hi,I have meet the same error,too!I was wonder if I have duplicate template in my code.And also I found your 'src' file had some strange things...I can't see 'CKEDITOR' import from anywhere....for example:
```
mounted () {
    let config = {
      toolbar: this.toolbar,
      language: this.language,
      height: this.height,
      extraPlugins: this.extraplugins
    }

    CKEDITOR.replace(this.id, config)

    this.instance.on('change', () => {
      let html = this.instance.getData()
      if (html !== this.value) {
        this.$emit('input', html)
      }
    })
  }
```
And here's my demo code.
```
<template>
  <div>
    <ckeditor v-model="test" :height="'300px'" :toolbar="[['Format']]"></ckeditor>
  </div>
</template>

<script>
  import Ckeditor from 'vue-ckeditor2'
  export default {
    data () {
      return {
        test: ''
      }
    },
    components: {
      Ckeditor
    }
  }
</script>
```
Thanks a lot...

**Comment by dangvanthanh** [comment]
@LeungKaMing So I'm using [webpack templates](https://github.com/vuejs-templates/webpack) to test. It's because I include script of ckeditor external, so in `ckeditor.vue` doesn't import `CKEDITOR`. You can include script in `index.html`

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>my-project</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
    <!-- built files will be auto injected -->
  </body>
</html>
```

And example and test with scripts

```js
<template>
  <div>
    <ckeditor v-model="content"></ckeditor>
  </div>
</template>

<script>
<template>
  <div>
    <ckeditor v-model="content"></ckeditor>
  </div>
</template>

<script>
import Ckeditor from 'vue-ckeditor2'

export default {
  name: 'hello-vue-ckeditor2',
  components: { Ckeditor },
  data () {
    return {
      content: 'Welcome to vue-ckeditor2'
    }
  }
}
</script>
```

It's working fine with me. Can you try again with the same code.

Thank you very much. I will write guide to use `vue-ckeditor2` when missing `ckeditor.js` library.

**Comment by hpaicf** [comment]
@dangvanthanh i have the same question, missing ckeditor.js library. do i have to include script of ckeditor external ? i have install ckeditor with npm, i don't want to include script of ckeditor external, is there other way to solve it ?
