### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by prorockdesign** [dangvanthanh/vue-ckeditor2#16]
Hello. I use Vue 2 (Vuex) and Laravel Elixir with Browserify to compile my files.
It gives me an error message: 

`<template>
^
ParseError: Unexpected token`

Other components in project work fine. All dependencies are up-to-date.
What am I doing wrong?

**Comment by dangvanthanh** [comment]
@prorockdesign I develop vue-ckeditor2 and bundle with Rollup and Webpack. I'm not use Laravel Elixir with Browserify. Can you show me code you using and I will fix it.

**Comment by dangvanthanh** [comment]
@prorockdesign May you missing `ckeditor.js` in the `index.html` file. `vue-ckeditor2` using ckeditor external.

```html
<script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
```

or

```html
<script src="/path/to/ckeditor.js"></script>
```

**Comment by prorockdesign** [comment]
Thanks. I thinks it will be great idea to note about adding script tag to index file in docs.
But your solution doesn't helps me. I copied `ckeditor.vue` to my project folder from `node_modules` and now all works fine. I really don't understand the difference of the file placement for Elixir+Browserify. I didn't meet this error before.
