### ISSUE TITLE
Adding plugins such as YouTube?

### ISSUE THREAD

**Issue by siddhant92** [dangvanthanh/vue-ckeditor2#19]
Is there a way to add extra plugins? Trying to embed a youtube video but looks like it's only possible through ck plugins: http://ckeditor.com/addon/youtube

**Comment by dangvanthanh** [comment]
You can add extra plugins. https://github.com/dangvanthanh/vue-ckeditor2/wiki/Toolbar#how-to-add-custom-toolbar
