### ISSUE TITLE
No "name" attribute preventing form from submitting content

### ISSUE THREAD

**Issue by bryanjamesmiller** [dangvanthanh/vue-ckeditor2#26]
Hi, I need to use this component apart from Ajax, so I need to have the "name" field on the textarea.  I made a PR as one example that should work for me, but I'd appreciate it if you could pull that in or make a similar addition?  Thank you!  PR:  https://github.com/dangvanthanh/vue-ckeditor2/pull/25/files?w=1

**Comment by dangvanthanh** [comment]
@bryanjamesmiller Thank you very much.
