### ISSUE TITLE
Using custom CKeditor instance in webpack boilerplate

### ISSUE THREAD

**Issue by focussing** [dangvanthanh/vue-ckeditor2#27]
How can I use a custom CKeditor build?
Using the vue-cli webpack boilerplate.
In .vue component I add
```
import CKEDITOR from 'ckeditor'
import Ckeditor from 'vue-ckeditor2'
```
Removed the CDN for CKeditor from index.html:
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Squarell DAP App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div id="app"></div>
  <!-- <script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script> -->
  <!-- built files will be auto injected -->
</body>

</html>
```
Now I get errors like

> ckeditor.js?7294:232 Uncaught TypeError: Cannot set property 'dir' of undefined
>     at Object.f (eval at <anonymous> (app.js:1206), <anonymous>:232:470)
>     at g (eval at <anonymous> (app.js:1206), <anonymous>:234:33)
>     at Array.n (eval at <anonymous> (app.js:1206), <anonymous>:234:188)
>     at p (eval at <anonymous> (app.js:1206), <anonymous>:234:272)
>     at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror (eval at <anonymous> (app.js:1206), <anonymous>:235:209)

**Comment by dangvanthanh** [comment]
I try your code and I have same this problem. I think if you want use custom Ckeditor instead of cdn, you need download Ckeditor from [Ckeditor](http://ckeditor.com/download) then configure [Specifying the Editor Path](http://docs.ckeditor.com/#!/guide/dev_basepath)

**Comment by focussing** [comment]
I know that, but how do I do that?

Which according the CKeditor needs to be solved like Specifying the Editor Path.
Did that several ways like the following, but nothing works.
What am I doing wrong?

```
var CKEDITOR_BASEPATH = './ckeditor/';
import axios from 'axios';
import CKEDITOR from 'ckeditor'
import Ckeditor from 'vue-ckeditor2'
```
