### ISSUE TITLE
Catch CKeditor events

### ISSUE THREAD

**Issue by focussing** [dangvanthanh/vue-ckeditor2#28]
How can I catch CKeditor events? Like described [here] (http://docs.ckeditor.com/#!/api/CKEDITOR.editor) 
For example when I use the editor inline and close the editor, I want to catch the blur event.

**Comment by focussing** [comment]
Dear Dang,

Found it by looking at the source code. See you $emit and I bind an event handler to that.

`<ckeditor :value="post.nl" types="inline" @change="onChange(index,$event)"></ckeditor>`

The only thing I can't get to work is this as described in the vuejs docs:

```
methods: {
    onChange: function (event, index) {
      // `this` inside methods points to the Vue instance
      alert('Hello ' + this.name + '!')
      // `event` is the native DOM event
      if (event) {
        alert(event.target.tagName)
      }
    }
  }
```

**Comment by dangvanthanh** [comment]
Hi @focussing 

I agree, I think there should more events. I want to custom component to easy add more events, too. I will research it and add soon.

**Comment by akinolu52** [comment]
hello @dangvanthanh 

i tried this:

`<ckeditor @blur="updateQuestion(questionIndex, $event)" :config="config"></ckeditor>`


`updateQuestion(i, e){
                console.log(i)
                this.examQuestions[i] = e.target.value;
                console.log(this.examQuestions)
            },`


but it is not showing in the console.

thanks in adv

**Comment by dangvanthanh** [comment]
Hi @akinolu52 

I will update version support **blur** and **focus** events in Ckeditor. Can you reference to using [blur and focus events](https://github.com/dangvanthanh/vue-ckeditor2/wiki/Getting-Started)

**Comment by dangvanthanh** [comment]
Hi @focussing 

Now you can update to using custom **blur** or **focus** events.

**Comment by akinolu52** [comment]
thanks it working now.

**Comment by akinolu52** [comment]
hello @dangvanthanh

thanks it working now. bt the only issue i have is that e.target.value; is not working when i
console.log(e) i cant get what i typed into the textarea any help?

**Comment by dangvanthanh** [comment]
Hi @akinolu52 

I use `CKEDITOR.instances` (this instance Ckeditor) register `blur` and `focus` events. With your code:

```js
<ckeditor @blur="updateQuestion(questionIndex, $event)" :config="config"></ckeditor>
```

You can show value of $event with

```js
updateQuestion(i, e) {
   console.log(e) // This instance of Ckeditor
   console.log(e.getData()) // Get value of Ckeditor
}
```

**Comment by akinolu52** [comment]
thanks @dangvanthanh. works like magic

**Comment by vaishnavi-prabakar** [comment]
Hi, 

We are trying to update something on our Vue component based on the mode change in CKEDITOR.

There is an event 'mode' emitted by CKEDITOR for the same. Can we please have a listener for that event in vue-ckeditor?
