### ISSUE TITLE
error in the firefox

### ISSUE THREAD

**Issue by m-alinasab** [dangvanthanh/vue-ckeditor2#30]
hello and thanks for this package :)

i used ckeditor package on vuejs template component .
but when type text on this textarea , my firefox Hang My Browser 

check this problem to other pc  and There is problem.
please see image : 

![photo_2017-07-11_15-12-35](https://user-images.githubusercontent.com/8689072/28064862-6a9d6f48-664b-11e7-8c2b-8b412527ebc6.jpg)

![photo_2017-07-11_15-12-29](https://user-images.githubusercontent.com/8689072/28064861-6a78dad4-664b-11e7-966c-05c23b5b2b27.jpg)

**Comment by dangvanthanh** [comment]
Hi @m-alinasab 

I use **Firefox 54.0.1**  on **Mac 10.12.6**. I was fine, no error such as you describe. Can you describe your Firefox and Os version.
