### ISSUE TITLE
Use vuejs in plugin

### ISSUE THREAD

**Issue by Remo** [dangvanthanh/vue-ckeditor2#31]
I've seen that we can easily add ckeditor plugins, that's great, but I'm trying to build a tight integrating with my project and for that I should have access to vuejs states and data. Is there a way to create a plugin that simply calls a VueJS method and then allows me to execute a ckeditor command to insert my custom code?

**Comment by dangvanthanh** [comment]
@Remo Now, I working and integrating Ckeditor with Vue.js. In the future, I will try integrating all methods from Ckeditor to Vue.js. Thank you very from your feedback.
