### ISSUE TITLE
[Suggestion] Offer script tag option for implementation

### ISSUE THREAD

**Issue by aijorgenson** [dangvanthanh/vue-ckeditor2#33]
For example, the plugin vue-focus uses cdnjs to provide an easy implementation: https://www.npmjs.com/package/vue-focus

Some users don't wish to use the Vue CLI in their projects.

**Comment by dangvanthanh** [comment]
Thank you for suggestion. I will publish to cdnjs or file for easy implementation.

**Comment by aijorgenson** [comment]
That sounds great, thank you!

**Comment by dangvanthanh** [comment]
@aijorgenson 

Sorry for implementation later. I publish script to `unpkg.com`, you can use script with

```html
<script src="https://unpkg.com/vue-ckeditor2"></script>
```
