### ISSUE TITLE
how to upload content of plugin to website?

### ISSUE THREAD

**Issue by caiyawen** [dangvanthanh/vue-ckeditor2#35]
I want to add a plugin of img upload,but i am confuse about the sentence 'upload content of plugin to website' at https://github.com/dangvanthanh/vue-ckeditor2/wiki/Toolbar. Is there someone could tell me the steps? thanks very much~

**Comment by huhongliang** [comment]
The button already exists,But it's hidden,Now I don't know where to configure

**Comment by dangvanthanh** [comment]
@huhongliang Can you show your code or your configure to display button. I will help you configure.

**Comment by heyluffy** [comment]
how to add a plugin of img upload, Is there someone could tell me the steps?

**Comment by LXHFIGHT** [comment]
how to add a plugin of youtube, Is there someone could tell me the steps?

**Comment by quangvision** [comment]
Hello Author,
Can you help because I still can't add extraPlugin like 'image2'? Thanks :)

**Comment by dangvanthanh** [comment]
Hi @quangvision 

I add guide to add `extraPlugin` like `image2`: https://github.com/dangvanthanh/vue-ckeditor2/wiki/Multiple-Plugins-with-extraPlugins and with demo in http://vue-ckeditor2.surge.sh/

**Comment by dangvanthanh** [comment]
Hi @hpaicf 

You can reference to intergrate [easyimage](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_easyimage.html) to `vue-ckeditor2`

This is example I use `Example.vue`

```vue
<template>
  <div id="app" class="app">
    <vue-ckeditor v-model="multiplePlugins.content" :config="multiplePlugins.config" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      multiplePlugins: {
        content:`
          <p>Use multiple plugins image2 and autogrow and easyimage</p>
          <figure class="easyimage easyimage-full">
            <img alt="Three Monks walking on ancient temple." width="912" sizes="100vw" src="https://cdn.dribbble.com/users/458522/screenshots/4615441/attachments/1043210/deadpool_love_add.jpg" />
            <figcaption></figcaption>
          </figure>
        `,
        config: {
          toolbar: [
            ['Image']
          ],
          height: 200,
          extraPlugins: 'image2,autogrow,xml,ajax,cloudservices,balloonpanel,balloontoolbar,imagebase,easyimage',
          emovePlugins: 'image',
          cloudServices_tokenUrl: 'https://33372.cke-cs.com/token/dev/kquv5QAPjvSD8p7GYFSFa3uKP6OcikCtjcyDpqW1Aqy3eotwe2pPLVdAjJVu',
          cloudServices_uploadUrl: 'https://33372.cke-cs.com/easyimage/upload/',
          autoGrow_minHeight: 200,
          autoGrow_maxHeight: 600
        }
      }
    };
  }
};
</script>

<style scoped>
.ckeditor {
  font-size: 13px;
}
</style>
```

`cloudServices_tokenUrl` and `cloudServices_uploadUrl` you can found in [Ckeditor Dashboard](https://dashboard.ckeditor.com/)

You can see using easyimage plugin in  [demo](https://vue-ckeditor2.surge.sh/) with **Multiple Plugins**
