### ISSUE TITLE
value exists, v-model added but ckeditor area is empty

### ISSUE THREAD

**Issue by shalakhin** [dangvanthanh/vue-ckeditor2#39]
![screenshot 2017-08-23 21 27 07](https://user-images.githubusercontent.com/433637/29631913-e6387fc4-8849-11e7-9309-078a8c36722d.png)

What might be wrong?

The code:

```js
export default {
  components: { Ckeditor },
  data () {
    return {
      id: null,
      name: null,
      body: null,
      order: null,
      config: {
        toolbar: [
          { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'] },
          { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
          { name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'SpecialChar'] },
          { name: 'basicstyles', items: ['Bold', 'Italic', 'Strike', '-', 'RemoveFormat'] },
          { name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'] },
          { name: 'styles', items: ['Styles', 'Format'] }
        ],
        height: 500
      }
    }
  },
  methods: {
    editLesson () {
      this.axios({
        method: 'patch',
        url: 'some-url',
        data: {
          'id': this.id,
          'name': this.name,
          'body': this.body,
          'order': this.order,
          'is_active': true
        },
        headers: {
          'Authorization': 'Token ' + this.$cookie.get('token'),
          'Content-Type': 'application/json'
        }
      }).then((data) => {
        this.$router.push({name: 'Dashboard Lessons'})
      })
    },
    updateLesson () {
      this.axios({
        method: 'get',
        url: 'some-url',
        headers: {
          'Authorization': 'Token ' + this.$cookie.get('token'),
          'Content-Type': 'application/json'
        }
      }).then((response) => {
        this.body = response.data.body
        this.name = response.data.name
        this.order = response.data.order
        this.id = response.data.id
        var at = this
        console.log(at)
      }).catch((error) => {
        console.log(error.response)
      })
    }
  },
  beforeMount () {
    this.updateLesson()
  }
}
```

**Comment by lavenkin** [comment]
I have the same problem

**Comment by manly0305** [comment]
Same for me . Can fix it soon ?

**Comment by shalakhin** [comment]
We have decided to try quill editor. The vuejs component words great and I like the lightweight design. But hope CKEditor component will receive the fix or maybe if our team finds time we will propose pull request with a fix.

**Comment by dangvanthanh** [comment]
@shalakhin I love Qill editor, too. Now I continue and fix vue-ckeditor. I hope our team will fix soon.

**Comment by killemalljustice** [comment]
Hi, I have the same problem, but if i make a change of the value in created() , like this:

```
created() {
     this.field = 'something';
}
```
it works as expected

[https://imgur.com/a/UkAi8](url)

but if i make a change from a method it does not work :(

```
agregaCodigo() {
       this.field = 'something';
}
```

[https://imgur.com/a/XLuBX](url)

**Comment by adnanshussain** [comment]
Yes, exactly the same issue as @killemalljustice 

When I fetch my data using ajax and the editor has already loaded it shows empty. However editing writing stuff in the editor updates the bound property correctly.

**Comment by dangvanthanh** [comment]
Thank for all. I was updated for fix.

**Comment by blooddrunk** [comment]
It seems to me that the editor will keep displaying the initial value of the mode defined in `data` object  when it creates, even if that value changes afterwards.

**Comment by ganlvtech** [comment]
I have created a new commit in my forked repo.  Added 3 lines in the VCkeditor.vue.

Edit in your node_modules/vue-ckeditor2/src/VCkeditor.vue to see if it helps.

I think if it really helps you, the commit can be merged.

Thanks.

**Comment by dangvanthanh** [comment]
Awesome. Thank you very much @ganlvtech

**Comment by megamiSoh** [comment]
Cool!!!!! Thanky you so much  Ganlvtech!
you are Genius!!!! yo man!!!
Thank you !!
