### ISSUE TITLE
Value sometimes not set

### ISSUE THREAD

**Issue by nWidart** [dangvanthanh/vue-ckeditor2#42]
Hello,

Thank you for this component!

I've got an issue were the value of ckeditor isn't filled. The weird part is this doesn't happen consistently but only some of the times.

The component call looks like so:

```js
<ckeditor v-model="page[locale].body" :value="page[locale].body">
</ckeditor>
```

I'm fetching and setting the page body via a remote call with axios.

When I `console.log(this.value)` in the value watcher of the ckeditor component, I do see my data logged, but the ckeditor instance isn't setting the data.

Also, when I set the value after initial page load, using `$vm0.page.en.body = 'asf'`, it doesn't set the ckeditor instance with that data. If however I change the watcher to:

```js
this.instance.setData(this.value)
```
Then it does set it via console call. It does still fail on page load though.

Is there something I need to do?

Thanks!

**Comment by nWidart** [comment]
It doesn't set the value of ckeditor, yet I do see this in console:

![image](https://user-images.githubusercontent.com/882397/30426360-0be914fa-994c-11e7-8e4f-e5747cf1031e.png)


when I add a `console.log(this.value, this.instance);` in the `value` watcher.

**Comment by dangvanthanh** [comment]
I was update in #39

**Comment by nWidart** [comment]
Hello,

I'm still getting the issue, on page reload, sometimes the editor is empty.

**Comment by dangvanthanh** [comment]
Hi @nWidart 

Can you update and check again for your issue.

**Comment by usolved** [comment]
I have the same issue. It seems only to happen with Internet Explorer 11. I'm using vue-ckedtor 1.18.0 and the latest CKeditor 4.

After the page loads I get the content with ajax and setting the ckeditor v-model data variable.

this.content = my_new_content;

...or with...

this.$refs.my_great_instance.instance.setData(my_new_content);

...results both in working about 90% of the time. 

When I set a initial value to "content" and then have the 10% of the time when the value could not be set afterwards, it shows the initial value instead.

**Comment by Untel** [comment]
Hey guys, had the same issue.
Now work for me using :value instead of v-model

**Comment by dangvanthanh** [comment]
Hi @Untel 

I will guide use `:value` instead of `v-model`.

Thank you very much.

**Comment by vicnoob** [comment]
> Hey guys, i had the same issue.
> Now work for me using :value instead of v-model

Is that :value is 1 way binding? You must use @input along with :value?
