### ISSUE TITLE
CkEditor on SPA, before destroy crash

### ISSUE THREAD

**Issue by nWidart** [dangvanthanh/vue-ckeditor2#43]
Hello,

I'm setting up a SPA, with on the form component ckeditor. When leaving that component and loading in another one, the following error occurs:

```
app.js:1089 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'clearCustomData' of null"
```

I've pinned it down to the following line:

```
this.instance.destroy()
```

Any idea how this could be fixed?

Thanks

**Comment by nWidart** [comment]
Current fix is to wrap a try/catch like so:

``` js
try {
    this.instance.destroy()
} catch (e) { }
```

Explained here: https://stackoverflow.com/questions/25034150/ck-editor-uncaught-typeerror-cannot-read-property-clearcustomdata-of-null-i

**Comment by dangvanthanh** [comment]
Hi @nWidart Thank you very much. I will update for vue-ckeditor component.

**Comment by nWidart** [comment]
Awesome. Do you happen to know I had to do this? It seems strange to me. It looks like the instance was already destroyed somehow.

**Comment by dangvanthanh** [comment]
I think error is resolve in #49
