### ISSUE TITLE
Error on delete/destroy

### ISSUE THREAD

**Issue by loeffel-io** [dangvanthanh/vue-ckeditor2#45]
Hey, 
i get this error when i delete/destroy the ckeditor (remove it from the DOM):

`Uncaught TypeError: Cannot read property 'getRanges' of null`

I don't get this error message when i click inside the ckeditor (focus) before i delete the item. Can u please check this. 

Thanks 👍

**Comment by dangvanthanh** [comment]
Hi what the method you use detele/destroy the ckeditor?

**Comment by renatosistemasvc** [comment]
I also have this error. Any solution?

The error appears when I enter and exit the page that has the ckeditor.

**Comment by loeffel-io** [comment]
Fixed in 1.11.0 👍

**Comment by renatosistemasvc** [comment]
I'm using the 

"vue-ckeditor2" version: "^ 1.16.0"
vuejs: "vue": "^2.4.2"

and I get the error opening the ckeditor and exit. 
if before leaving I focus on ckeditor the error does not appear

my erro:

`Uncaught TypeError: Cannot read property 'getRanges' of null
`
Any solution?

**Comment by dangvanthanh** [comment]
Duplicate of #49

**Comment by SidFeng** [comment]
![image](https://user-images.githubusercontent.com/6702354/44030285-f328693c-9f32-11e8-8667-fb49a6190c2d.png)
same problem

**Comment by dangvanthanh** [comment]
Hi @SidFeng 

I was fixed in `2.0.10`. Detail fix in #49
