### ISSUE TITLE
setReadOnly(true) for onBlur, setReadOnly(fasle) for onFocus

### ISSUE THREAD

**Issue by david-j-davis** [dangvanthanh/vue-ckeditor2#46]
Any idea if this works with the native ckeditor setReadOnly method?

`methods: {
    onBlur (editor) {
      editor.setReadOnly( true );
    },
    onFocus (editor) {
      editor.setReadOnly( false );
    }
  }`

**Comment by ivanvermeyen** [comment]
Hi,

I tried this with a local copy of this component:

Added a new prop:

```js

readonly: {
    type: Boolean,
    default: false
}
```

Added a watcher:

```js
readonly(readonly) {
    this.instance.setReadOnly(readonly)
}
```

And at the end of the `create()` method I added:

```js
CKEDITOR.on('instanceReady', (event) => {
    // Change the read-only state of the editor.
    // http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-setReadOnly
    event.editor.setReadOnly(this.readonly)
});
```

Since the components emits `blur` events etc., the calling code could just update the `readonly` prop value whenever appropriate?

Just an idea :)

**Comment by dangvanthanh** [comment]
Hi @david-j-davis 

I have added `blur` and `focus` event for `vue-ckeditor2`. You can reference: https://github.com/dangvanthanh/vue-ckeditor2/wiki/Getting-Started

Thank you for idea @ivanvermeyen
