### ISSUE TITLE
CKEditor configuration/bug - content not posting after editing from the source

### ISSUE THREAD

**Issue by nWidart** [dangvanthanh/vue-ckeditor2#48]
Hello,

After editing the source of a page within CKEditor and clicking save (without navigating anywhere else within the editor), the new contents are not synced.

Expected: Editing using the source view of the CKEditor should sync the content - not the seemingly unchanged WYSIWYG view contents.

### Steps to reproduce

* Select the `Source` toolbar option in the CKEditor
* Edit something in the editor
* In vue dev tools, the content hasn't been synced

#### Steps to workaround

Toggling the source view back to normal view, syncs the content.

Thanks,

**Comment by mariglenjahollari** [comment]
Facing the same issue. Another workaround would be to just write something in the WYSIWYG. That will also sync the content.

**Comment by dangvanthanh** [comment]
Please upgrade to `2.0.3`. It will sync the content.
