### ISSUE TITLE
Error in destroying instance

### ISSUE THREAD

**Issue by renatosistemasvc** [dangvanthanh/vue-ckeditor2#49]
**VERSION:**

"vue": "^2.4.2"
"vue-ckeditor2": "^1.16.0"
"webpack": "^3.7.1"

**ERROR**

`Uncaught TypeError: Cannot read property 'getRanges' of null`

**SOLICITATION**

replacement of the function that destroys the instance. 

**DETAILS**

I would like to congratulate you on your good work.

I encountered a problem of vue-ckeditor2 the moment he tries to destroy the instance.
You are destroying the instance in vue-ckeditor2/src/VCkeditor.vue:

```
destroy () {
   if (!this.destroyed) {
        this.instance.focusManager.blur(true)
        this.instance.removeAllListeners()
        this.instance.destroy()
        this.destroyed = true
   }
}
```
for some reason the instance was not being properly destroyed. I searched the repository of ckeditor and they ask to use the following statement:

```
destroy () {
   CKEDITOR.instances[this.id].destroy()
}
```

I tested it here and it worked correctly with the statement CKEDITOR.instances[this.id].destroy().
Could you review a library update? I do not want to need to change the core of the library manually.

thank you

**Comment by mrmnmly** [comment]
and I receive something like this (e.g. when leaving route with CKEditor inside) :
```
[CKEDITOR] Error code: editor-destroy-iframe.
ckeditor.js:19:258
[CKEDITOR] For more information about this error go to https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_errors-section-editor-destroy-iframe
```

**Comment by renatosistemasvc** [comment]
change the core to the following code:

```
if (!this.destroyed) {

          this.instance.focusManager.blur(true);
          CKEDITOR.removeAllListeners();
          this.instance.destroy(true);
          this.destroyed = true;
}
```

I was able to solve the problem of destroying

**Comment by dangvanthanh** [comment]
Thank you very much @renatosistemasvc

**Comment by renatosistemasvc** [comment]
@dangvanthanh 
Thanks for answering. You still need a change:

the method ` .removeAllListeners();` does not exist in each specific instance. we can check if using a console.log in `console.log(this.instance);`. Note that this method does not exist. This method belongs to the higher instance `CKEDITOR.removeAllListeners();`.

that is... instead of using this:

`this.instance.removeAllListeners();`

You should use this:

`CKEDITOR.removeAllListeners();`

**using** `this.instance.removeAllListeners();`

![image](https://user-images.githubusercontent.com/15252973/40625267-b8fffdfc-6287-11e8-9633-345d7781395e.png)

**using** `CKEDITOR.removeAllListeners();`

![image](https://user-images.githubusercontent.com/15252973/40625306-ec69e518-6287-11e8-8948-3406b75ddf82.png)

**The method for destroying must be as follows:**

```
destroy: function destroy() {

        try {
          if (!this.destroyed) {

            this.instance.focusManager.blur(true);
            CKEDITOR.removeAllListeners();
            this.instance.destroy(true);
            this.destroyed = true;
          }
        } catch (e) {}
},
```
Hope this helps! and thank you for the excellent library.

**Comment by dangvanthanh** [comment]
Awesome @renatosistemasvc.

**Comment by mrmnmly** [comment]
I'm using latest `vue-ckeditor2` and latest `CKEditor 4` - problem still persists (only on chrome, it works fine on Firefox)

**Comment by dangvanthanh** [comment]
HI @lukaszkups 

We was fix destroy ckeditor instance correctly.
