### ISSUE TITLE
Caret jumps to beginning of editor when typing quickly on Firefox

### ISSUE THREAD

**Issue by helmoski** [dangvanthanh/vue-ckeditor2#53]
## Steps to reproduce:

1. Visit http://vue-ckeditor2.surge.sh/ in Firefox.
2. Type as quickly as you can.

Caret will jump to beginning of input.

(I'm using Firefox 52.5.3 on macOS Sierra 10.12.6)

## Demo:

![vue-ckeditor2-bug](https://user-images.githubusercontent.com/8516113/35355970-b308915e-0114-11e8-9193-80aea39751c1.gif)

**Comment by dangvanthanh** [comment]
Thank you very much @helmoski
