### ISSUE TITLE
trying to set content off vue editor not working

### ISSUE THREAD

**Issue by riksnelders** [dangvanthanh/vue-ckeditor2#55]
When changin model, data in editor is not changing.
Any solution to this?

**Comment by dangvanthanh** [comment]
Hi, @riksnelders. Can you show your code?

**Comment by riksnelders** [comment]
Hi @dangvanthanh .
Fixed it just running undo command like so 

`CKEDITOR.currentInstance.execCommand('undo');`

and give user a warning :)

**Comment by dangvanthanh** [comment]
Thank you very much @riksnelders 

I will write the wiki for the user a warning such as a case you see.
