### ISSUE TITLE
Multiple plugins?

### ISSUE THREAD

**Issue by ljungqvist93** [dangvanthanh/vue-ckeditor2#56]
It there a way of adding multiple extraPlugins?

Like:

extraPlugins: 'autogrow, embed'

**Comment by dangvanthanh** [comment]
Hi, you can add multi plugins with config.

```
config: {
  toolbar: [
    [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]
  ],
  height: 300,
  extraPlugins: 'autogrow,embed'
}
```

**Comment by dangvanthanh** [comment]
@ljungqvist93 

I add guide to add more plugins: https://github.com/dangvanthanh/vue-ckeditor2/wiki/Multiple-Plugins-with-extraPlugins

**Comment by quangvision** [comment]
Hi, 
I don't understand this 'download your plugin you want to integrate'. I downloaded plugin 'image2' but don't know where to put within my folders. I installed vue-ckeditor2 with npm. Please explain more. Thanks :)

**Comment by dangvanthanh** [comment]
Hi @quangvision 

You can setup ckeditor with path (folder you define) and put `image2` in `plugins` folder such as:

<img width="349" alt="ckeditor-vue-folder" src="https://user-images.githubusercontent.com/2674850/39665069-137c7530-50b8-11e8-9383-c0ba00a81e3d.png">

And in `index.html` you can use

```html
<script src="assets/js/ckeditor/ckeditor.js"></script>
<script src="assets/js/app.js"></script>
```

**Comment by cyrusonline** [comment]
could you give an example folder?

**Comment by dangvanthanh** [comment]
Hi @cyrusonline 

You can see [demo example](https://github.com/dangvanthanh/surge/tree/master/vue-ckeditor2) of using `vue-ckeditor2`

**Comment by dangvanthanh** [comment]
Can you send mail email I will zip and send source code for you?

**Comment by cyrusonline** [comment]
> Can you send your email I will zip and send source code for you?

yes, thank you , i just sent you an email

**Comment by cyrusonline** [comment]
Actually are you using webpack version?
As i must use cdn rather than using 
  <script src="ckeditor/ckeditor.js"></script>

**Comment by dangvanthanh** [comment]
I use [Vue CLI 3](https://cli.vuejs.org/)

**Comment by cyrusonline** [comment]
> Can you send your email I will zip and send source code for you?

Could you send me a sample source code, thank you

**Comment by dangvanthanh** [comment]
Hi @cyrusonline 

I was sent example for you. Please see in your email.

**Comment by cyrusonline** [comment]
> Hi @cyrusonline
> 
> I was sent example for you. Please see in your email.

Thank you very much

**Comment by BerezhniyDmitro** [comment]
hi i want to use
https://ckeditor.com/cke4/addon/googleDospastePlugin

I add a line

extraPlugins: 'googleDocPastePlugin',

and get an error. http://img.netpeak.ua/maestro/_12032019(013).png  What am I doing wrong?

**Comment by dangvanthanh** [comment]
Do you want use `googleDocPastePlugin`

https://ckeditor.com/cke4/addon/googleDocPastePlugin

If you use CDN Ckeditor please instead of you link of ckeditor

```
https://cdn.ckeditor.com/4.6.2/full/ckeditor.js
```

to newest of ckeditor

```
https://cdn.ckeditor.com/4.11.3/full-all/ckeditor.js
```

or 

```
https://cdn.ckeditor.com/4.6.2/full-all/ckeditor.js
```

If you use your path of ckeditor you need extract the downloaded plugin `googleDocPastePlugin` (`.zip` file) into the plugins folder of your CKEditor installation.

**Comment by BerezhniyDmitro** [comment]
I tried, the same errors (

http://img.netpeak.ua/maestro/_12032019(014).png

I use as a component vue
vue version 2.5.16

Thanks for the quick response =)

**Comment by dangvanthanh** [comment]
Hi @BerezhniyDmitro 

You should use ckeditor. You use `https://cdn.ckeditor.com/4.6.2/full/ckeditor.js`, just need modify to

```
https://cdn.ckeditor.com/4.6.2/full-all/ckeditor.js
```

**Comment by BerezhniyDmitro** [comment]
thanks for the answer.The situation has not changed.
http://img.netpeak.ua/maestro/_13032019.png

**Comment by BerezhniyDmitro** [comment]
solved the problem by downloading and installing not through cdn. Thank you )

**Comment by dangvanthanh** [comment]
See reference for not use cnd: https://github.com/dangvanthanh/vue-ckeditor2/issues/56#issuecomment-386815687
