### ISSUE TITLE
How to apply Placeholder

### ISSUE THREAD

**Issue by jeck5895** [dangvanthanh/vue-ckeditor2#60]
Hello I've tried applying Placeholder on the configuration but it's not working.
Here is my sample code:

`config: {
          toolbar: [
              ['Paste','PasteFromWord','Undo', 'Redo'],
              ['Others'],
              [ 'Bold', 'Italic', 'Heading' ],
              ['Link'],
              ['NumberedList', 'BulletedList','Source','Blockquote' ,'Preview'],
              ['Indent','Align']
          ],
          extraPlugins:'placeholder',
          placeholder:'<ul><li>Male / Female</li><li>Graduate of Internal Auditing / Accountancy or any related Business course</li><li>With at least minimum of 6 months experience on the same field but not necessary</li><li>With above average of communication skills in both oral and written English</li><li>Proficient in MS Office</li><li>Willing to be assigned in Pasig City and willing to do periodic travels to Batangas, Laguna, Cavite and Clark areas</li><li>Open to all fresh graduates&nbsp;</li></ul>',
          height: 200
        }`

**Comment by dangvanthanh** [comment]
Hi @jeck5895 

You can apply `Placeholder` such as:

```vue
<template>
  <div>
    <vue-ckeditor v-model="multiplePlugins.content" :config="multiplePlugins.config" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      multiplePlugins: {
        content:`
          <p>Use multiple plugins placeholder</p>
          <ul><li>Male / Female</li><li>Graduate of [[Internal Auditing]] / Accountancy or any related Business course</li><li>With at least minimum of 6 months experience on the same field but not necessary</li><li>With above average of communication skills in both oral and written English</li><li>Proficient in MS Office</li><li>Willing to be assigned in Pasig City and willing to do periodic travels to Batangas, Laguna, Cavite and Clark areas</li><li>Open to all fresh graduates&nbsp;</li></ul>
        `,
        config: {
          toolbar: [
            ['CreatePlaceholder']
          ],
          height: 200,
          extraPlugins: 'placeholder'
        }
      }
    };
  }
};
</script>
```

You can see [Demo](http://vue-ckeditor2.surge.sh/) in **Multiple Plugins**

**Comment by jeck5895** [comment]
Thank you so much appreciate it 😀
