### ISSUE TITLE
使用这个插件需要先引用ckeditor吗？

### ISSUE THREAD

**Issue by zhupp034** [dangvanthanh/vue-ckeditor2#62]
发现使用的时候报错，说miss ckeditor，这个插件里面没有集成是不是？是不是需要先引用

**Comment by dangvanthanh** [comment]
Hi @zhupp034 

I warning missing Ckeditor when you're not include script

https://github.com/dangvanthanh/vue-ckeditor2/blob/43e96592e95707b9e7a3b097b3c7ce92774ee68d/src/index.js#L73-L74

**Comment by zhupp034** [comment]
也就是说，需要先引用ckeditor.js之后，再使用你们这个插件是吗？
