### ISSUE TITLE
Catch CKEditor mode event

### ISSUE THREAD

**Issue by vaishnavi-prabakar** [dangvanthanh/vue-ckeditor2#63]
Hi,

We are trying to update something on our Vue component based on the mode change in CKEDITOR.

There is an event 'mode' emitted by CKEDITOR for the same. Can we please have a listener for that event in vue-ckeditor?

**Comment by Dabnis** [comment]
While you are at this (hopefully) could you also expose CkEditor change event.
Thanks

**Comment by dangvanthanh** [comment]
It fix in #74
