### ISSUE TITLE
Use with CKEditor npm package

### ISSUE THREAD

**Issue by IanBurry** [dangvanthanh/vue-ckeditor2#64]
This works great when I use CKEditor from a CDN, but not when I try to use it as a package via npm, or yarn. When doing it that way, I get 'CKEDITOR is missing.' Is there something I'm missing, or am I just out of luck?

**Comment by dangvanthanh** [comment]
Hi @IanBurry 

Currently, Ckeditor 4 doesn't full support via npm. You can see [Ckeditor 4](https://www.npmjs.com/package/ckeditor) on npm.

Now the better you can use from CDN or local files.
