### ISSUE TITLE
How to add mentions to the running instance.

### ISSUE THREAD

**Issue by stacybot123** [dangvanthanh/vue-ckeditor2#66]
I want to attach mentions plugin to the running instance to of the ckeditor , how can I add that to this.
It will be awesome if we can attach plugin like https://github.com/fritx/vue-at to the running instance of Ckeditor.

Thank you for creating this awesome plugin!!

**Comment by dangvanthanh** [comment]
Now you can use `instanceReadyCallback` to running instance of Ckeditor. Update by #68 @fernandomm.
