### ISSUE TITLE
VueJs 2.5.16 Failed to mount component

### ISSUE THREAD

**Issue by jbmchd** [dangvanthanh/vue-ckeditor2#69]
How to fix???

![image](https://user-images.githubusercontent.com/4037524/42725525-4ab5e282-875b-11e8-8448-ee98c0458ecc.png)

**Comment by dangvanthanh** [comment]
Hi @jbmchd 

I use with `Vue 2.5.16`. I don't see error `Failed wto mount component`. Can you post your code?

**Comment by jbmchd** [comment]
In app.js
![image](https://user-images.githubusercontent.com/4037524/42726891-99b47d8c-8772-11e8-833b-77de883b5d38.png)

In app.blade.php
![image](https://user-images.githubusercontent.com/4037524/42726899-c8b6d6e8-8772-11e8-8960-45691b3b454b.png)

In index.blade.php
![image](https://user-images.githubusercontent.com/4037524/42726915-07f2d488-8773-11e8-8f72-b6201cf2d153.png)

**Comment by dangvanthanh** [comment]
Can you try again with `v2.0.9`
