### ISSUE TITLE
Ckeditor is not displaying

### ISSUE THREAD

**Issue by unickortega** [dangvanthanh/vue-ckeditor2#70]
This dependency is really interesting for me and I appreciate your work , as I am still new in vue js
but I am having difficulty on trying to use your dependency.

![untitled](https://user-images.githubusercontent.com/20767859/42855134-aae18a4e-8a71-11e8-837e-857087b4f545.png)

Ckeditor is not displaying on my end.
It only appears as if it is hidden.
I've followed all starter procedures but it still doesn't work.

It would be a great help if you could fix this.
Thank you very much!

**Comment by dangvanthanh** [comment]
Hi @unickortega 

Can you post your code you use with `vue-ckeditor2`

**Comment by vbarkasov** [comment]
I have this problem too.
Can you make simple example of vue-ckeditor2 with one of boilerpalte templates?

**Comment by dangvanthanh** [comment]
I can getting started in here: https://vue-ckeditor2.surge.sh/#getting-started

I used [rollup boilerplate](https://github.com/dangvanthanh/vue-rollup-boilerplate) and [webpack boilerplate](https://github.com/vuejs-templates/webpack)

**Comment by vbarkasov** [comment]
I did everything according to instructions. Not working. What did I do wrong?
