### ISSUE TITLE
Ckeditor destroys itself

### ISSUE THREAD

**Issue by dermansi** [dangvanthanh/vue-ckeditor2#71]
Hey,

great component!

We are using your ckeditor in a tab component and on calling the tab with the ckeditor the editor destroys itself while throwing the following error:

Uncaught TypeError: Cannot read property 'unselectable' of null

Using the latest vue2 and vue-ckeditor2 version with the latest ckeditor 4.

Any insights? I am kinda lost here.

Thanks
dermansi

**Comment by dangvanthanh** [comment]
Thank @dermansi 

I will investigate issue and fix soon it.

**Comment by dermansi** [comment]
Thank you @dangvanthanh ,

just message me if you need any help or more information on this topic.

**Comment by dermansi** [comment]
Hey @dangvanthanh,

any progress on this issue? We are using the editor in this tab component https://github.com/spatie/vue-tabs-component

The ckeditor destroys itself after switching between the tabs (the editor is on the second tab, the first on gets focused on page load)

Thanks in advance
dermansi

**Comment by dangvanthanh** [comment]
Hi @dermansi 

I write example with your component `vue-tabs-component` but doesn't see error you describe

[Example with Vue Tabs Component](http://vue-ckeditor2.surge.sh/examples/)

**Comment by dangvanthanh** [comment]
Hi @dermansi 

This is my error. I see occur `Error code: editor-destroy-iframe` when swich page from `Classic` to `Inline`. I will fix soon

**Comment by dermansi** [comment]
Hey @dangvanthanh,

thank you for your time. I'll try to reproduce the issue in a fiddle.

**Comment by Cookizza** [comment]
Any update on this?

**Comment by dangvanthanh** [comment]
Hi @Cookizza 

Bug was fixed in #49

**Comment by dermansi** [comment]
It seems like it fixed my problem, thank you!
