### ISSUE TITLE
Model do not change when showing source

### ISSUE THREAD

**Issue by Leshgan** [dangvanthanh/vue-ckeditor2#74]
vue-ckeditor2 version is 2.0.6
When I click on "Source" button and editing html code, the model of component doesn't change.

**Comment by dangvanthanh** [comment]
Hi @Leshgan 

I use [vue-devtools](https://github.com/vuejs/vue-devtools) I see `v-model` is `content` change and updated. 

![vue-ckeditor2-v2 0 6](https://user-images.githubusercontent.com/2674850/43724068-59611cb4-99c3-11e8-8b02-38565da74aa3.gif)

**Comment by Leshgan** [comment]
Hi, @dangvanthanh! Thanks for the answer.
On ckeditor panel I have button "source" to show source code of text with html tags right in editor. When in this mode, model not changing

**Comment by Leshgan** [comment]
@dangvanthanh 
![screencast 2018-08-06 18-01-33](https://user-images.githubusercontent.com/966961/43724565-f46e49a0-99a2-11e8-95b8-f4b6be7a9348.gif)
