### ISSUE TITLE
How to import ckeditor locally?

### ISSUE THREAD

**Issue by DKWBL** [dangvanthanh/vue-ckeditor2#77]
I've installed ckeditor via npm.
If i import ckeditor from 'ckeditor' i get unexpected tokens errors.

If i link it as you advise  - via <script ....> in index.html - everything works fine.

Is there a better way to link your component and ckeditor? Thanks

**Comment by DKWBL** [comment]
Thanks for reply.
But in case of npm - how to get your component to find ckeditor?

**Comment by mrmnmly** [comment]
I'm also interested in that - I've tried already this:

```
import Ckeditor from 'vue-ckeditor2'
require('ckeditor')
```

But I receive an error: `TypeError: c[a] is undefined` from CKEditor file.
