### ISSUE TITLE
How Can I customize the toolbar?

### ISSUE THREAD

**Issue by Silwady** [dangvanthanh/vue-ckeditor2#78]
I want to customize toolbar to show more options, I tried to add more  actions like **justify | center | right | left** or **upload | link** and so on.

I don't know why it just shows the origin buttons

`
        toolbar: [
          ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
        ],
`

**Comment by Silwady** [comment]
I found the solution, It is a case sensitive, it should be **Link** instead **link**

I found list of values in this link

https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#advanced

**Comment by dangvanthanh** [comment]
Beside list in Ckeditor. You can found here

[Toolbar Ckeditor](https://github.com/dangvanthanh/vue-ckeditor2/wiki/Toolbar)
