### ISSUE TITLE
Latest changes broke my app

### ISSUE THREAD

**Issue by picululu** [dangvanthanh/vue-ckeditor2#80]
Hey. 

I have automatic minor updates in my app and the package stopped working in the latest version here. I have now downgraded and it works again. 
I have no idea what caused it, it did not give an error, just completely broke.

**Comment by dangvanthanh** [comment]
Hi @picululu 

Can you share code why not working?

**Comment by picululu** [comment]
Well.. pretty standard implementation i guess.. 

`<template lang="html">
    <vue-ckeditor v-model="text" :config="config" types="classic" @blur="onBlur()" @focus="onFocus()"></vue-ckeditor>
</template>
`

**Comment by dangvanthanh** [comment]
Hi I use `vue-ckeditor2` version `v2.0.9` with [demo classic](https://vue-ckeditor2.surge.sh/classic/)

**Comment by picululu** [comment]
Maybe the CKEditor version? I have 4.9.2

**Comment by dangvanthanh** [comment]
I have Ckeditor `4.10.0` too
