### ISSUE TITLE
local import fail

### ISSUE THREAD

**Issue by abnerwang0991** [dangvanthanh/vue-ckeditor2#82]
I have download ckeditor 4 , and put it into the root directory of vue cli project.

in index.html
<script src="/ckeditor/ckeditor.js"></script>
![ckeditor](https://user-images.githubusercontent.com/33473028/45595041-fdaed200-b9d7-11e8-8a52-0fea11529290.PNG)

I'm sure the path is correct, but it would throw  'CKEDITOR is missing' in console.
It would not occur in a cdn way.

**Comment by dangvanthanh** [comment]
Hi @abnerwang0991  You need move `ckeditor` folder to `public` folder.
