### ISSUE TITLE
custom toolbar + all properties of config object

### ISSUE THREAD

**Issue by BilalAfzalRebel** [dangvanthanh/vue-ckeditor2#87]
Anybody helps me to add custom button on toolbar. The one explaining on this link: https://github.com/dangvanthanh/vue-ckeditor2/wiki/Toolbar doesn't make me understand.

**Comment by dangvanthanh** [comment]
Hi @BilalAfzalRebel 

You can see example to add custom button on toolbar https://github.com/dangvanthanh/surge/blob/master/vue-ckeditor2/.vuepress/components/Classic.vue

**Comment by BilalAfzalRebel** [comment]
hi @dangvanthanh 
there isn't anything like below?
editor = CKEDITOR.replace('editor', {
            fullPage: true,
            allowedContent: true,
            language: "en",
            height: 500,
        });

  editor.ui.addButton('SuperButton', {  // to add button
            label: "Media Gallery",
            command: 'mySimpleCommand', //command name to execute on button click
            icon: "someImageLink"
        });
        editor.addCommand("mySimpleCommand", {  execute command on added button
            exec: function (execute) {
                alert("here");
            }
        });

**Comment by BilalAfzalRebel** [comment]
i have tried you code in my component and got this error:
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "image2" was not found at "https://cdn.ckeditor.com/4.10.0/standard/plugins/image2/plugin.js?t=I63C".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:263)
    at e (ckeditor.js:258)
    at Array.y (ckeditor.js:258)
    at v (ckeditor.js:258)
    at HTMLScriptElement.A.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:259)

**Comment by dangvanthanh** [comment]
Hi @BilalAfzalRebel 

```javascript
CKEDITOR.replace('editor', options);
```

Your code is if instance of [Ckeditor 4](https://ckeditor.com/ckeditor-4/). With `vue-ckeditor2`, I wrapper Ckeditor with [Vue.js](https://vuejs.org/). You can reference Ckeditor and use with Vue.js.

You try demo missing `image2` because you use standard of Ckeditor.

You need change url ckeditor is full of Ckeditor:

```
https//cdn.ckeditor.com/4.10.0/full-all/ckeditor.js
```

**Comment by BilalAfzalRebel** [comment]
hi @dangvanthanh 
i have tried your code from this link: https://github.com/dangvanthanh/surge/blob/master/vue-ckeditor2/.vuepress/components/Classic.vue in my component and got this error:
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "image2" was not found at "https://cdn.ckeditor.com/4.10.0/standard/plugins/image2/plugin.js?t=I63C".
at CKEDITOR.resourceManager. (ckeditor.js:263)
at e (ckeditor.js:258)
at Array.y (ckeditor.js:258)
at v (ckeditor.js:258)
at HTMLScriptElement.A.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:259)
