### ISSUE TITLE
vue-runtime-helpers Reference Added

### ISSUE THREAD

**Issue by pplusawork** [dangvanthanh/vue-ckeditor2#89]
This may not be an issue, so feel free to just close this, but just so it's documented in case anyone else runs into it:

Commit [c837b26](https://github.com/dangvanthanh/vue-ckeditor2/commit/c837b267b9e02d1b58bf357c966c9dbc794ca03b) added a reference to vue-runtime-helpers, but it didn't get pulled in as a dependency when running npm install, so I had to add a reference to vue-runtime-helpers in my package.json.

The specific error that popped up in my CI pipeline was:
```
This dependency was not found:
* vue-runtime-helpers/dist/normalize-component.js in ./node_modules/vue-ckeditor2/dist/vue-ckeditor2.esm.js
```

**Comment by dangvanthanh** [comment]
This is maybe my vault when I upgrade version of bili. I will fix soon. Thanks @pplusawork

**Comment by dangvanthanh** [comment]
Hi @pplusawork 

The dependency `vue-runtime-helpers` was removed.
