### ISSUE TITLE
List of toolbar components

### ISSUE THREAD

**Issue by crow1796** [dangvanthanh/vue-ckeditor2#9]
Where can I find the list of all toolbar components?

I tried using this toolbar:
`[
					{ name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
					{ name: 'editing', items : [ 'Find','Replace','-','SelectAll','-'] },
					{ name: 'forms', items : [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 
				        'HiddenField' ] },
					'/',
					{ name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
					{ name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv',
					'-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
					{ name: 'links', items : [ 'Link','Unlink'] },
					{ name: 'insert', items : [ 'Image','Table','HorizontalRule','SpecialChar','PageBreak'] },
					'/',
					{ name: 'styles', items : [ 'Styles','Format','Font','FontSize' ] },
					{ name: 'colors', items : [ 'TextColor','BGColor' ] },
				]`

But only these components appeared:
![image](https://cloud.githubusercontent.com/assets/12120770/22636197/79aa3ab2-ec74-11e6-942b-57fbd90def13.png)

Text Align is missing.

**Comment by dangvanthanh** [comment]
You can find [list toolbar of ckeditor](http://nightly.ckeditor.com/17-02-06-07-07/full/samples/toolbarconfigurator/index.html#advanced).

Some toolbar missing because maybe you use standard of ckeditor:

```html
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
```

You can instead of with full of ckeditor: 

```html
<script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
```

You can understand more about ckeditor by reference: [Ckeditor 4 Documentation](http://docs.ckeditor.com/)
