### ISSUE TITLE
Expose an 'change' event to allow detecting when text changes

### ISSUE THREAD

**Issue by StephanusRex** [dangvanthanh/vue-ckeditor2#98]
**Is your feature request related to a problem? Please describe.**
The OnBlur/OnFocus are not sufficient for detecting changes. 

**Describe the solution you'd like**
I would like a "change" event on the editor so we can react accordingly.

**Describe alternatives you've considered**
I tried using a watcher; however, this gets fired at inappropriate times which causes the auto-save feature I'm working on to work incorrectly.

**Additional context**

**Comment by dangvanthanh** [comment]
Thank your feedback @StephanusRex 

Currently for `change` event you can use `@input` event such as

```javascript
<vue-ckeditor 
      v-model="content" 
      :config="config" 
      @input="onInput($event)" />
```

**Comment by StephanusRex** [comment]
Excellent! Thanks!
______________________
Sincerely,

Steven M. King

**Comment by dangvanthanh** [comment]
@StephanusRex 

I will include in `README`. Thanks.
