### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by StephanusRex** [dangvanthanh/vue-ckeditor2#99]
This isn't actually a feature request so I apologize for that but I've tried the CKEditor site and can't get anywhere with my question.

I'm not sure how to configure the toolbar in my code. I just have the default toolbar but I need at least font colors (background/foreground) and would like to add some more. The Toolbar Configuration tool from CKEditor is nice but I'm not sure what to do with the code.

Sorry, I'm still a n00b and just looking for some direction. Thanks in advance.

**Comment by dangvanthanh** [comment]
Sample toolbar you can reference [here](https://github.com/dangvanthanh/vue-ckeditor2/wiki/Toolbar).

You should use `Full Package` of [Ckeditor](https://ckeditor.com/ckeditor-4/download/) for full toolbar

**Comment by StephanusRex** [comment]
I'm using the following code to specify config but it's being ignored. Just below the `data() { return ... }` function is the **components: { VueCkeditor }**, by the way.

![image](https://user-images.githubusercontent.com/24681303/63276386-479bda00-c271-11e9-939a-0dd567c4893a.png)

What am I doing wrong that the config isn't working?

Thanks in advance.

**Comment by StephanusRex** [comment]
Ignore the last post/question. I had inadvertently omitted the **:config="config"** attribute.
